# Generated by Django 5.2.8 on 2025-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tematica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
